=== tnkhuong/NABAPI/src/test/resources/contracts/CurrentWeatherSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "coord": {
      "type": "object",
      "properties": {
        "lon": {
          "type": "number"
        },
        "lat": {
          "type": "number"
        }
      }
    },
    "weather": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer"
            },
            "main": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "icon": {
              "type": "string"
            }
          }
        }
      ]
    },
    "base": {
      "type": "string"
    },
    "main": {
      "type": "object",
      "properties": {
        "temp": {
          "type": "number",
          "minimum": 250,
          "maximum": 320
        },
        "feels_like": {
          "type": "number"
        },
        "temp_min": {
          "type": "number"
        },
        "temp_max": {
          "type": "number"
        },
        "pressure": {
          "type": "integer"
        },
        "humidity": {
          "type": "integer"
        }
      }
    },
    "visibility": {
      "type": "integer"
    },
    "wind": {
      "type": "object",
      "properties": {
        "speed": {
          "type": "number"
        },
        "deg": {
          "type": "integer"
        }
      }
    },
    "clouds": {
      "type": "object",
      "properties": {
        "all": {
          "type": "integer"
        }
      }
    },
    "dt": {
      "type": "integer"
    },
    "sys": {
      "type": "object",
      "properties": {
        "type": {
          "type": "integer"
        },
        "id": {
          "type": "integer"
        },
        "country": {
          "type": "string"
        },
        "sunrise": {
          "type": "integer"
        },
        "sunset": {
          "type": "integer"
        }
      }
    },
    "timezone": {
      "type": "integer"
    },
    "id":{
      "type": "integer"
    },
    "name":{
      "type": "string"
    },
    "cod": {
      "type": "integer"
    }
  },
  "required": ["id", "name", "coord", "weather", "base", "main", "visibility", "wind", "clouds", "dt", "sys", "timezone","cod"]
}

=== tnkhuong/NABAPI/src/main/resources/apiresponses/CurrentWeatherResponse.json
{
    "id": 2643743,
    "coord": {
      "lon": -0.1257,
      "lat": 51.5085
    },
    "weather": [
      {
        "id": 804,
        "main": "Clouds",
        "description": "overcast clouds",
        "icon": "04d"
      }
    ],
    "base": "stations",
    "main": {
      "temp": 285.84,
      "feels_like": 284.89,
      "temp_min": 284.82,
      "temp_max": 287.04,
      "pressure": 1010,
      "humidity": 66
    },
    "visibility": 10000,
    "wind": {
      "speed": 2.06,
      "deg": 330
    },
    "clouds": {
      "all": 90
    },
    "dt": 1621005765,
    "sys": {
      "type": 1,
      "id": 1414,
      "country": "GB",
      "sunrise": 1620965402,
      "sunset": 1621021429
    },
    "timezone": 3600,
    "name": "London",
    "cod": 200
}
